"""Google Login MCP workflow for the built-in browser.

Provides a structured workflow that guides the AI agent to assist the user
in signing into their Google account via the MCP browser, using backup/recovery
codes for 2FA. This avoids phone-based verification that can't be automated.

Recovery codes are pre-generated by the user from their Google Account settings.
"""
import json
import sys
from pathlib import Path


def _find_project_root():
    curr = Path(__file__).resolve().parent
    while curr != curr.parent:
        if (curr / "tool.json").exists() and (curr / "bin" / "TOOL").exists():
            return curr
        curr = curr.parent
    return Path(__file__).resolve().parent.parent.parent.parent.parent

_project_root = _find_project_root()
if str(_project_root) not in sys.path:
    sys.path.insert(0, str(_project_root))

from logic.interface.config import get_color

BOLD = get_color("BOLD")
GREEN = get_color("GREEN")
RED = get_color("RED")
BLUE = get_color("BLUE")
YELLOW = get_color("YELLOW")
RESET = get_color("RESET")

GOOGLE_LOGIN_URL = "https://accounts.google.com/signin"
RECOVERY_CODES_URL = "https://myaccount.google.com/signinoptions/two-step-verification"


def build_recovery_codes_tutorial():
    """Return instructions for obtaining Google recovery codes."""
    return {
        "title": "How to Get Google Recovery Codes",
        "url": RECOVERY_CODES_URL,
        "steps": [
            "Open https://myaccount.google.com/signinoptions/two-step-verification in your regular browser.",
            "Sign in to your Google account if prompted.",
            "Scroll down to the 'Backup codes' section.",
            "Click 'Show codes' (or 'Set up' if not configured yet).",
            "Copy or save the 10 backup codes displayed.",
            "Each code is 8 digits and can only be used once.",
            "Store these codes securely (e.g., password manager).",
            "You can regenerate codes at any time (invalidates old ones).",
        ],
        "note": "Recovery codes bypass phone-based 2FA, enabling login in "
                "environments where phone verification is not possible (like the IDE browser).",
    }


def build_login_workflow(email=None, recovery_code=None):
    """Build a structured MCP workflow for Google account login.

    Args:
        email: Google account email address (optional, prompted if missing).
        recovery_code: One of the user's recovery codes (optional, prompted if missing).

    Returns:
        dict with workflow steps for the AI agent to execute.
    """
    steps = [
        {
            "step": 1,
            "action": "navigate",
            "description": "Open Google sign-in page",
            "mcp_tool": "browser_navigate",
            "args": {"url": GOOGLE_LOGIN_URL},
        },
        {
            "step": 2,
            "action": "lock",
            "description": "Lock browser for automation",
            "mcp_tool": "browser_lock",
            "args": {},
        },
        {
            "step": 3,
            "action": "snapshot",
            "description": "Get page state to find email input",
            "mcp_tool": "browser_snapshot",
            "args": {},
        },
        {
            "step": 4,
            "action": "enter_email",
            "description": "Type email into the identifier field",
            "mcp_tool": "browser_fill",
            "args": {"ref": "find:textbox:Email or phone", "value": email or "<USER_EMAIL>"},
            "note": "The email field ref name may vary. Look for textbox with name containing 'Email', 'email', or 'identifier'.",
            "requires_input": not bool(email),
        },
        {
            "step": 5,
            "action": "click_next",
            "description": "Click 'Next' button after email",
            "mcp_tool": "browser_click",
            "args": {"ref": "find:button:Next"},
        },
        {
            "step": 6,
            "action": "wait_password",
            "description": "Wait for password page to load",
            "mcp_tool": "browser_wait_for",
            "args": {"text": "Enter your password", "timeout": 10000},
            "note": "The page transitions to password entry. Wait for it to load.",
        },
        {
            "step": 7,
            "action": "enter_password",
            "description": "Enter the account password",
            "note": "The agent should ask the user for their password via USERINPUT. "
                    "NEVER type the password into the chat. Use browser_fill to enter it directly.",
            "mcp_tool": "browser_fill",
            "args": {"ref": "find:textbox:Enter your password", "value": "<USER_PASSWORD>"},
            "requires_input": True,
            "sensitive": True,
        },
        {
            "step": 8,
            "action": "click_next_password",
            "description": "Click 'Next' button after password",
            "mcp_tool": "browser_click",
            "args": {"ref": "find:button:Next"},
        },
        {
            "step": 9,
            "action": "check_2fa",
            "description": "Check if 2-Step Verification is required",
            "mcp_tool": "browser_snapshot",
            "args": {},
            "note": "After password, Google may show a 2FA challenge. "
                    "Look for 'Try another way' link to switch to recovery codes.",
            "conditional": True,
        },
        {
            "step": 10,
            "action": "select_recovery_code_method",
            "description": "Click 'Try another way' to access recovery code option",
            "mcp_tool": "browser_click",
            "args": {"ref": "find:link:Try another way"},
            "note": "On the 2FA page, click 'Try another way' to see alternative verification methods.",
            "conditional": True,
        },
        {
            "step": 11,
            "action": "select_backup_codes",
            "description": "Select 'Enter one of your 8-digit backup codes'",
            "mcp_tool": "browser_click",
            "args": {"ref": "find:*:backup code"},
            "note": "Look for a link or button mentioning 'backup code' or 'recovery code'. "
                    "The exact text varies by locale.",
            "conditional": True,
        },
        {
            "step": 12,
            "action": "enter_recovery_code",
            "description": "Enter the recovery/backup code",
            "mcp_tool": "browser_fill",
            "args": {"ref": "find:textbox:Enter code", "value": recovery_code or "<RECOVERY_CODE>"},
            "note": "Enter one of the 8-digit backup codes. Each code can only be used once.",
            "requires_input": not bool(recovery_code),
            "sensitive": True,
        },
        {
            "step": 13,
            "action": "click_next_recovery",
            "description": "Click 'Next' to verify the recovery code",
            "mcp_tool": "browser_click",
            "args": {"ref": "find:button:Next"},
        },
        {
            "step": 14,
            "action": "verify_login",
            "description": "Verify login succeeded",
            "mcp_tool": "browser_snapshot",
            "args": {},
            "note": "Check if the page redirects to Google account or shows the user's profile. "
                    "If login failed, the page will show an error message.",
        },
        {
            "step": 15,
            "action": "unlock",
            "description": "Unlock browser",
            "mcp_tool": "browser_unlock",
            "args": {},
        },
    ]

    return {
        "status": "workflow",
        "action": "google_login",
        "login_url": GOOGLE_LOGIN_URL,
        "email": email,
        "steps": steps,
        "recovery_codes_tutorial": build_recovery_codes_tutorial(),
        "tips": {
            "password_security": "Never ask the user to type their password in chat. "
                                 "Use USERINPUT to collect it, then browser_fill to enter it.",
            "recovery_codes": "Each recovery code can only be used once. The user should have "
                              "multiple codes available.",
            "2fa_variations": "Google's 2FA flow varies. The agent may need to adapt steps 9-13 "
                              "based on what the page actually shows.",
            "session_persistence": "Once logged in, the browser session persists. Subsequent "
                                   "operations (Colab, Drive) will use this session.",
        },
    }


def run_mcp_login(email=None, recovery_code=None, as_json=False):
    """Generate MCP login workflow.

    Returns exit code: 0 = success (workflow printed)
    """
    workflow = build_login_workflow(email=email, recovery_code=recovery_code)

    if as_json:
        print(json.dumps(workflow, indent=2))
    else:
        print(f"{BOLD}{BLUE}Google Login MCP Workflow{RESET}")
        print(f"  Login URL: {GOOGLE_LOGIN_URL}")
        if email:
            print(f"  Account: {email}")
        print()
        print(f"  {BOLD}Prerequisites:{RESET}")
        print(f"  1. Have your Google account email ready.")
        print(f"  2. Have your account password ready.")
        print(f"  3. Have at least one recovery code ready.")
        print()
        print(f"  {BOLD}How to get recovery codes:{RESET}")
        print(f"  Visit: {RECOVERY_CODES_URL}")
        print(f"  (Sign in > 2-Step Verification > Backup codes > Show codes)")
        print()
        print(f"  Use {BOLD}GOOGLE --mcp-login --json{RESET} for structured workflow instructions.")
    return 0
