import signal
import sys
import json
import time
import threading
import platform
import subprocess
import os
import queue
from pathlib import Path
from typing import Optional, Dict, Any, Callable, List, Union

# Lazy import for tkinter to support auto-reexecution with safe python
tk = None

def _get_tk():
    global tk
    if tk is None:
        import tkinter as _tk
        tk = _tk
    return tk

# Centralized list of noise patterns generated by Tkinter/macOS IMK
TK_NOISE_PATTERNS = [
    "IMKClient subclass", 
    "IMKInputSession subclass", 
    "chose IMKClient_Legacy", 
    "chose IMKInputSession_Legacy",
    "invalid command name",
    "check_signals",
    "after script",
    "TK_SILENCE_DEPRECATION",
    "<lambda>",
    "destroying",
    "main_frame"
]

def filter_tkinter_noise(stderr_content: str) -> str:
    """
    Filters out common Tkinter/macOS system noise from stderr.
    """
    if not stderr_content:
        return ""
    lines = stderr_content.splitlines()
    filtered_lines = [l for l in lines if not any(p in l for p in TK_NOISE_PATTERNS)]
    return "\n".join(filtered_lines).strip()

try:
    from logic.gui.tkinter.style import get_label_style, get_button_style, get_status_style, get_gui_colors, get_secondary_label_style
    from logic.lang.utils import get_translation
except ImportError:
    # Fallbacks for standalone execution
    def get_label_style(): return ("Arial", 10)
    def get_secondary_label_style(): return ("Arial", 9, "italic")
    def get_button_style(primary=False): return ("Arial", 10, "bold" if primary else "normal")
    def get_status_style(): return ("Arial", 11)
    def get_gui_colors(): return {"blue": "#007AFF", "green": "#28A745", "red": "#DC3545", "pulse": "#004085"}
    def get_translation(d, k, default): return default

class BaseGUIWindow:
    """
    Blueprint for Tool GUIs with timeout, signal handling, and state management.
    """
    def __init__(self, title: str, timeout: int, internal_dir: str, tool_name: str = None):
        self.title = title
        self.remaining_time = timeout
        self.internal_dir = internal_dir
        self.tool_name = tool_name
        self.root = None
        self.window_closed = False
        self.result = {"status": "error", "data": None}
        self.pulse_active = False # Flag to avoid timer overwriting pulse status
        
        # Shared behavior state
        self.focus_interval = 0
        self.bell_path = str(Path(__file__).resolve().parent.parent.parent.parent / "asset" / "audio" / "bell.mp3")
        self.is_triggering_subtool = False
        self.add_time_increment = 60 # Default
        self.submit_btn = None # To be linked in setup_common_bottom_bar
        self.cancel_btn = None
        self.add_time_btn = None
        self.bottom_bar_frame = None
        self.timer_frozen = False
        
        # Image management for dynamic resizing
        self.resizable_images: List[Dict[str, Any]] = [] # {label, path, max_width, upscale, original_img}
        
        # Block management
        self.blocks: List[Any] = []
        self.debug_blocks = False # If True, blocks will have visible backgrounds
        
        # Thread safety: queue for callbacks from background threads
        self.callback_queue = queue.Queue()
        
        # Robust project root detection for flags and audio
        from logic.utils import find_project_root
        if self.internal_dir and isinstance(self.internal_dir, (str, Path)):
            self.project_root = find_project_root(Path(self.internal_dir))
        else:
            # Fallback to current working directory
            self.project_root = find_project_root(Path.cwd())

        # Signal registration
        signal.signal(signal.SIGINT, self.handle_external_signal)
        signal.signal(signal.SIGTERM, self.handle_external_signal)

    def _(self, key: str, default: str, **kwargs) -> str:
        # 1. Try tool-specific translation
        val = get_translation(self.internal_dir, key, None)
        if val is None:
            # 2. Try shared GUI component translation (from logic/gui/translation)
            val = get_translation(str(self.project_root / "logic"), key, default)
        return val.format(**kwargs)

    def handle_external_signal(self, signum, frame):
        """Gracefully close on external signals, capturing current state."""
        if not self.window_closed:
            stop_file = self.project_root / "data" / "run" / "stops" / f"{os.getpid()}.stop"
            reason = "signal"
            if stop_file.exists():
                reason = "stop"
            
            self.finalize("terminated", self.get_current_state(), reason=reason)
            
            # Print result before exiting from signal handler
            print("GDS_GUI_RESULT_JSON:" + json.dumps(self.result), flush=True)
            
            sys.exit(128 + signum)

    def check_signals(self):
        """Periodic check to allow Python to process signals and check for stop flags."""
        if not self.window_closed and self.root:
            # Check project root for data/run/stops/
            try:
                stops_dir = self.project_root / "data" / "run" / "stops"
                
                # Detect flags for this PID
                pid = os.getpid()
                
                # 1. STOP flag
                stop_file = stops_dir / f"{pid}.stop"
                if stop_file.exists():
                    stop_file.unlink()
                    self.finalize("terminated", self.get_current_state(), reason="stop")
                    return

                # 2. SUBMIT flag
                submit_file = stops_dir / f"{pid}.submit"
                if submit_file.exists():
                    submit_file.unlink()
                    self.finalize("success", self.get_current_state())
                    return

                # 3. CANCEL flag
                cancel_file = stops_dir / f"{pid}.cancel"
                if cancel_file.exists():
                    cancel_file.unlink()
                    self.finalize("cancelled", self.get_current_state())
                    return

                # 4. ADD_TIME flag
                add_time_file = stops_dir / f"{pid}.add_time"
                if add_time_file.exists():
                    add_time_file.unlink()
                    # Trigger the add_time pulse if possible
                    if hasattr(self, "on_remote_add_time"):
                        self.on_remote_add_time()
                    else:
                        # Fallback if no specific callback
                        self.remaining_time += self.add_time_increment
                        if not sys.stdout.isatty():
                            print(f"GDS_GUI_TIME_ADDED:{self.add_time_increment}", flush=True)
            except Exception:
                pass

            # Schedule next check
            try: self.root.after(500, self.check_signals)
            except: pass

    def start_timer(self, status_label: Any):
        """Standardized countdown timer."""
        import tkinter as tk
        if self.window_closed: return
        
        # Save default color if not already saved
        if not hasattr(self, '_default_status_fg'):
            self._default_status_fg = status_label.cget("fg")

        if not self.pulse_active:
            try:
                rem_msg = self._('time_remaining', 'Remaining:')
                status_label.config(text=f"{rem_msg} {self.remaining_time}s", fg=self._default_status_fg)
            except: pass
        
        if self.remaining_time > 0:
            if not self.timer_frozen:
                self.remaining_time -= 1
            if self.root:
                self.root.after(1000, lambda: self.start_timer(status_label))
        else:
            # Capture State A and return via Interface I
            self.finalize("timeout", self.get_current_state())

    def play_bell(self):
        """Standard bell notification logic using unified interface."""
        if self.root:
            try: self.root.bell()
            except: pass
        
        from logic.utils import find_project_root
        project_root = find_project_root(Path(self.internal_dir))
        from logic.gui.engine import play_notification_bell
        play_notification_bell(project_root)

    def start_periodic_focus(self, interval: int):
        """Starts periodic refocusing and bell."""
        self.focus_interval = interval
        if self.focus_interval <= 0: return
        
        def refocus():
            if not self.window_closed and self.root:
                if not self.is_triggering_subtool:
                    try:
                        self.root.lift()
                        self.root.attributes("-topmost", True)
                        self.play_bell()
                    except: pass
                self.root.after(self.focus_interval * 1000, refocus)
        
        if self.root:
            self.root.after(self.focus_interval * 1000, refocus)

    def finalize(self, status: str, data: Any, reason: Optional[str] = None):
        """Unified closure point (Interface I). status: success, cancelled, timeout, terminated, error."""
        if not self.window_closed:
            self.window_closed = True
            self.result = {"status": status, "data": data}
            if reason:
                self.result["reason"] = reason
            try:
                if self.root:
                    self.root.update_idletasks()
                    self.root.destroy()
            except: pass

    def trigger_add_time(self, increment: int, status_label: Optional[Any] = None):
        """
        Atomically increments remaining time, notifies parent, and updates UI.
        The signal notification happens BEFORE UI updates.
        """
        # 1. Signal Parent (via flag file for atomicity and avoiding stdout pollution)
        try:
            from logic.utils import find_project_root
            project_root = find_project_root(Path(self.internal_dir))
            added_time_dir = project_root / "data" / "run" / "added_time"
            added_time_dir.mkdir(parents=True, exist_ok=True)
            # Use a unique file for each add event to ensure they are all processed
            ts = time.time()
            flag_file = added_time_dir / f"{os.getpid()}_{ts}_{increment}.add"
            flag_file.touch()
        except:
            pass

        # 2. Update Internal State
        self.remaining_time += increment
        self.pulse_active = True
        
        # 3. Update UI
        if status_label and not self.window_closed:
            added_msg = self._("time_added", "Time added!")
            status_label.config(text=f"{added_msg} {self.remaining_time}s", fg=get_gui_colors()["pulse"])
            
            def reset_pulse():
                if not self.window_closed:
                    self.pulse_active = False
                    rem_msg = self._('time_remaining', 'Remaining:')
                    status_label.config(text=f"{rem_msg} {self.remaining_time}s", fg=self._default_status_fg)
            
            self.root.after(2000, reset_pulse)

    def get_current_state(self) -> Any:
        """Subclasses MUST override this to return their current state (State A)."""
        return None

    def add_block(self, parent, pady=10, padx=0, bg=None):
        """Adds a new layout block (tk.Frame) that fills the width."""
        import tkinter as tk
        block_bg = bg
        if not block_bg:
            if getattr(self, "debug_blocks", False):
                # Light alpha-like colors for visual debugging
                colors = ["#e8f0fe", "#fdf7e3", "#f6f6f6", "#e6fffa", "#fff5f5"]
                idx = len(self.blocks) % len(colors)
                block_bg = colors[idx]
            else:
                block_bg = parent.cget("bg")
                
        # block should fill the width of its parent
        block = tk.Frame(parent, bg=block_bg)
        block.pack(fill=tk.X, side=tk.TOP, padx=padx, pady=pady)
        self.blocks.append(block)
        return block

    def setup_image(self, parent, image_path: Union[str, Path], max_width: int = None, max_height: int = None, upscale: int = 2, dynamic: bool = True):
        """
        Loads and displays an image in a tkinter Label with quality control.
        upscale: Multiplier for internal rendering resolution (clearer images). Default to 2 for 1x clearer.
        dynamic: If True, the image will resize when its parent container resizes.
        """
        from PIL import Image, ImageTk
        import tkinter as tk
        
        try:
            img_path_str = str(image_path)
            img = Image.open(img_path_str)
            
            # Create label first, we'll configure it in resize
            label = tk.Label(parent, bg=parent.cget("bg"))
            label.pack(pady=10, fill=tk.X)
            
            item = {
                "label": label,
                "path": img_path_str,
                "max_width": max_width,
                "max_height": max_height,
                "upscale": upscale,
                "original_img": img,
                "parent": parent
            }
            
            if dynamic:
                self.resizable_images.append(item)
                # Bind to the block's resize event
                if not hasattr(parent, "_resize_bound"):
                    parent.bind("<Configure>", self.on_container_resize, add="+")
                    parent._resize_bound = True
            
            # Initial resize call with a bit more delay to ensure layout is ready
            self.root.after(100, lambda: self._resize_single_image(item))
            return label
        except Exception as e:
            import tkinter as tk
            print(f"Error loading image {image_path}: {e}")
            err_label = tk.Label(parent, text=f"Error loading image: {os.path.basename(str(image_path))}", fg="red")
            err_label.pack(pady=5)
            return err_label

    def _resize_single_image(self, item):
        """Internal logic for a single image resize. Target width = Block width."""
        from PIL import ImageTk, Image
        import tkinter as tk
        
        label = item["label"]
        try:
            if not label.winfo_exists(): return
        except tk.TclError: return
            
        parent = item["parent"]
        original_img = item["original_img"]
        upscale = item["upscale"]
        
        # 1. Get actual available width in the block
        parent_w = parent.winfo_width()
        
        # 2. If parent_w is 1 (not rendered yet), try to get from window width
        if parent_w <= 1:
            if self.root:
                # Use update_idletasks sparingly to avoid recursion
                # self.root.update_idletasks()
                parent_w = parent.winfo_width()
            
            if parent_w <= 1:
                parent_w = self.root.winfo_width() - 80 if self.root else 720
        
        # 3. Check if we actually need to resize to avoid jitter
        last_w = item.get("last_w", 0)
        # Only resize if the width change is significant (> 5px) or it's the first time
        if last_w > 0 and abs(parent_w - last_w) < 5:
            return

        # 4. Target width is the parent width (container width)
        target_w = parent_w
        if target_w < 50: target_w = 50
        
        # 5. Apply max_width if provided
        if item.get("max_width"):
            target_w = min(target_w, item["max_width"])
        
        item["last_w"] = parent_w
        
        orig_w, orig_h = original_img.size
        # Calculate aspect ratio
        aspect = orig_h / orig_w
        target_h = int(target_w * aspect)
        
        # 5. Apply max_height if provided
        if item["max_height"] and target_h > item["max_height"]:
            target_h = item["max_height"]
            target_w = int(target_h / aspect)
        
        if self.debug_blocks:
            print(f"DEBUG: Resizing image {os.path.basename(item['path'])}")
            print(f"  Parent width: {parent_w}, Calculated target_w: {target_w}, Target height: {target_h}")

        try:
            # Render at upscale resolution for clarity
            render_w, render_h = int(target_w * upscale), int(target_h * upscale)
            resized_img = original_img.resize((render_w, render_h), Image.Resampling.LANCZOS)
            photo = ImageTk.PhotoImage(resized_img)
            label.config(image=photo)
            label.image = photo 
        except Exception as e:
            if self.debug_blocks:
                print(f"DEBUG: Resize error for {item['path']}: {e}")

    def setup_label(self, parent, text, font=None, pady=5, padx=0, justify="left", is_title=False):
        """Standardized label creation with automatic wrapping."""
        import tkinter as tk
        if "[" in text and "]" in text and "(" in text and ")" in text:
            # Contains links, use inline link logic
            return self.add_inline_links(parent, text)

        if font is None:
            from logic.gui.tkinter.style import get_label_style
            if is_title:
                font = ("Arial", 22, "bold")
            else:
                font = get_label_style()
            
        # Initial wraplength based on parent width
        w = parent.winfo_width()
        if w <= 1: 
            if self.root:
                # self.root.update_idletasks() # Use sparingly
                w = parent.winfo_width()
            if w <= 1: w = 700
        
        # Labels should fill the width of the block
        # We use a small margin of 10 to avoid clipping
        label = tk.Label(parent, text=text, font=font, bg=parent.cget("bg"), 
                         justify=tk.CENTER if is_title else justify, 
                         wraplength=max(50, w-10))
        label.pack(pady=pady, padx=padx, fill=tk.X)
        
        if self.debug_blocks:
            label.config(highlightthickness=1, highlightbackground="#ccc")

        # Ensure parent has resize binding
        if not hasattr(parent, "_resize_bound"):
            parent.bind("<Configure>", self.on_container_resize, add="+")
            parent._resize_bound = True
            
        return label

    def add_inline_links(self, frame, text_content):
        """
        Creates a tk.Text widget that supports inline clickable links.
        Format: "Some text [Link Label](https://link.url) and more text."
        """
        import webbrowser
        import re
        import tkinter as tk
        
        text_widget = tk.Text(frame, wrap=tk.WORD, font=get_label_style(), 
                              padx=20, pady=10, borderwidth=0, highlightthickness=0,
                              bg=frame.cget("bg"), height=1) 
        text_widget.pack(fill=tk.X, expand=True)
        
        # Make it look like a label
        text_widget.config(state=tk.NORMAL)
        
        # Regex for [label](url)
        pattern = r'\[([^\]]+)\]\(([^)]+)\)'
        
        last_idx = 0
        for match in re.finditer(pattern, text_content):
            # Normal text before link
            text_widget.insert(tk.END, text_content[last_idx:match.start()])
            
            # Link label
            label, url = match.groups()
            tag_name = f"link_{match.start()}"
            text_widget.insert(tk.END, label, tag_name)
            
            text_widget.tag_config(tag_name, foreground="blue", underline=True)
            text_widget.tag_bind(tag_name, "<Enter>", lambda e: text_widget.config(cursor="hand2"))
            text_widget.tag_bind(tag_name, "<Leave>", lambda e: text_widget.config(cursor="arrow"))
            text_widget.tag_bind(tag_name, "<Button-1>", lambda e, u=url: webbrowser.open_new(u))
            
            last_idx = match.end()
            
        # Remaining text
        text_widget.insert(tk.END, text_content[last_idx:])
        
        # Disable editing
        text_widget.config(state=tk.DISABLED)
        
        def _update_height(event=None):
            # Adjust height based on content
            try:
                num_lines = int(text_widget.index('end-1c').split('.')[0])
                text_widget.config(height=num_lines)
            except: pass

        frame.bind("<Configure>", _update_height, add="+")
        _update_height()
        
        return text_widget

    def on_container_resize(self, event):
        """Callback for container <Configure> events to handle dynamic image and text wrapping."""
        # Only trigger updates if width changed significantly to avoid jitter from height-only changes
        # (e.g. from image/text wrapping itself changing height)
        # We store the last width on the parent object
        prev_w = getattr(event.widget, "_last_config_w", 0)
        if prev_w > 0 and abs(event.width - prev_w) < 5:
            return
        event.widget._last_config_w = event.width

        # Use a small delay to avoid excessive resizing during active drag
        if hasattr(self, "_resize_timer"):
            self.root.after_cancel(self._resize_timer)
        self._resize_timer = self.root.after(100, self.perform_ui_updates)

    def perform_ui_updates(self):
        """Actual resizing logic for images and text wrapping."""
        if self.window_closed or not self.root:
            return
        self.perform_image_resizing()
        self.perform_text_wrapping_updates()

    def perform_image_resizing(self):
        """Actual resizing logic for all registered dynamic images."""
        for item in list(self.resizable_images):
            self._resize_single_image(item)

    def perform_text_wrapping_updates(self):
        """Updates wraplength for all Labels within blocks to match current width."""
        import tkinter as tk
        if self.window_closed or not self.root: return
        
        # Traverse all widgets and find Labels with wraplength
        def update_labels(container):
            for child in container.winfo_children():
                if isinstance(child, tk.Label):
                    try:
                        # Only update if it already has a non-zero wraplength (meaning it's intended to wrap)
                        curr_wrap = child.cget("wraplength")
                        if curr_wrap and int(curr_wrap) > 0:
                            # Set wraplength to parent width minus a small margin of 10
                            parent_w = container.winfo_width()
                            if parent_w > 10:
                                child.config(wraplength=parent_w - 10)
                    except: pass
                elif isinstance(child, tk.Frame):
                    update_labels(child)
        
        # Start from blocks or main frame
        for block in self.blocks:
            try:
                if block.winfo_exists():
                    update_labels(block)
            except: pass

    def process_callbacks(self):
        """Process callbacks from other threads (thread-safe UI updates)."""
        if self.window_closed or not self.root:
            return
            
        try:
            while True:
                callback = self.callback_queue.get_nowait()
                callback()
        except queue.Empty:
            pass
        except Exception:
            pass
            
        if not self.window_closed and self.root:
            self.root.after(100, self.process_callbacks)

    def run(self, setup_func: Callable, on_show: Optional[Callable] = None, custom_id: Optional[str] = None):
        """Main execution flow."""
        import tkinter as tk
        try:
            if platform.system() == "Darwin":
                # Suppress IMKClient noise by redirecting stderr temporarily at FD level
                # Keep it redirected until UI is fully setup to catch late noise
                fd = os.open(os.devnull, os.O_WRONLY)
                old_stderr = os.dup(sys.stderr.fileno())
                os.dup2(fd, sys.stderr.fileno())
                try:
                    self.root = tk.Tk(className=self.__class__.__name__)
                    self.root.title(self.title)
                    setup_func()
                finally:
                    # Sync and restore
                    sys.stderr.flush()
                    os.dup2(old_stderr, sys.stderr.fileno())
                    os.close(fd)
                    os.close(old_stderr)
            else:
                self.root = tk.Tk()
                self.root.title(self.title)
                setup_func()
            
            # Start background pollers
            self.check_signals()
            self.process_callbacks()
            
            # 1. Register instance for registry-based stop
            try:
                from logic.utils import find_project_root
                project_root = find_project_root(Path(self.internal_dir))
                instance_dir = project_root / "data" / "run" / "instances"
                instance_dir.mkdir(parents=True, exist_ok=True)
                self.instance_file = instance_dir / f"gui_{os.getpid()}.json"
                with open(self.instance_file, "w") as f:
                    json.dump({
                        "pid": os.getpid(), 
                        "tool_name": self.tool_name,
                        "title": self.title, 
                        "custom_id": custom_id, # Added
                        "class": self.__class__.__name__,
                        "start_time": time.time()
                    }, f)
            except:
                self.instance_file = None

            self.root.protocol("WM_DELETE_WINDOW", lambda: self.finalize("cancelled", self.get_current_state()))
            
            if on_show is not None:
                self.root.after(100, on_show)

            # Bring to front (Interface I behavior)
            self.root.lift()
            self.root.attributes("-topmost", True)

            if platform.system() == "Darwin":
                # Suppress IMKClient noise during mainloop too
                fd = os.open(os.devnull, os.O_WRONLY)
                old_stderr = os.dup(sys.stderr.fileno())
                os.dup2(fd, sys.stderr.fileno())
                try:
                    self.root.mainloop()
                finally:
                    sys.stderr.flush()
                    os.dup2(old_stderr, sys.stderr.fileno())
                    os.close(fd)
                    os.close(old_stderr)
            else:
                self.root.mainloop()
            
            # Cleanup stop files if they exist for this PID
            try:
                from logic.utils import find_project_root
                project_root = find_project_root(Path(self.internal_dir))
                stops_dir = project_root / "data" / "run" / "stops"
                pid = os.getpid()
                for ext in ["stop", "submit", "cancel", "add_time"]:
                    f = stops_dir / f"{pid}.{ext}"
                    if f.exists(): f.unlink()
            except: pass

            # Cleanup registry
            if hasattr(self, 'instance_file') and self.instance_file and self.instance_file.exists(): 
                try: self.instance_file.unlink()
                except: pass
                
            # Print final result for parent process to capture (Interface I)
            # Use a more explicit check for managed mode
            is_managed = (os.environ.get("GDS_GUI_MANAGED") == "1")
            
            result_line = "GDS_GUI_RESULT_JSON:" + json.dumps(self.result)
            if is_managed:
                sys.stdout.write("\n" + result_line + "\n")
                sys.stdout.flush()
        except Exception as e:
            if hasattr(self, 'instance_file') and self.instance_file and self.instance_file.exists():
                try: self.instance_file.unlink()
                except: pass
            import traceback
            traceback.print_exc()
            self.result = {"status": "error", "message": str(e)}
            result_line = "GDS_GUI_RESULT_JSON:" + json.dumps(self.result)
            if os.environ.get("GDS_GUI_MANAGED") == "1":
                sys.stdout.write("\n" + result_line + "\n")
                sys.stdout.flush()

def setup_common_bottom_bar(parent, window_instance: BaseGUIWindow, 
                            submit_text: str, submit_cmd: Callable,
                            add_time_increment: int = 60) -> Any:
    """
    Creates a standardized bottom bar with status, countdown, and buttons.
    Returns: status_label
    """
    import tkinter as tk
    window_instance.add_time_increment = add_time_increment
    bottom_frame = tk.Frame(parent)
    window_instance.bottom_bar_frame = bottom_frame # Store for hiding
    
    # Standard padding matching USERINPUT style
    bottom_frame.pack(side=tk.BOTTOM, fill=tk.X, padx=15, pady=(5, 15))
    
    # Status label (left)
    status_label = tk.Label(bottom_frame, text="", font=get_status_style())
    status_label.pack(side=tk.LEFT)
    
    # Primary Button (right)
    # Store it in window_instance if it has the attribute
    submit_btn = tk.Button(bottom_frame, text=submit_text, command=submit_cmd, 
                           font=get_button_style(primary=True))
    submit_btn.pack(side=tk.RIGHT)
    if hasattr(window_instance, "submit_btn"):
        window_instance.submit_btn = submit_btn
    
    # Add Time Button (right)
    if add_time_increment > 0:
        add_msg = window_instance._("add_time", "Add {seconds}s", seconds=add_time_increment)
        def on_add_time():
            window_instance.trigger_add_time(add_time_increment, status_label)
        
        # Register for remote trigger
        window_instance.on_remote_add_time = on_add_time
            
        add_btn = tk.Button(bottom_frame, text=add_msg, command=on_add_time, 
                            font=get_button_style())
        add_btn.pack(side=tk.RIGHT, padx=(0, 10))
        window_instance.add_time_btn = add_btn # Store for hiding
    
    # Cancel Button (right)
    cancel_btn = tk.Button(bottom_frame, text=window_instance._("btn_cancel", "Cancel"), 
                           command=lambda: window_instance.finalize("cancelled", window_instance.get_current_state()), 
                           font=get_button_style())
    cancel_btn.pack(side=tk.RIGHT, padx=(0, 10))
    window_instance.cancel_btn = cancel_btn # Store for hiding
    
    return status_label
