# Standard library information used by the traceback module for more informative
# ModuleNotFound error messages.
# Generated by check_extension_modules.py

_MISSING_STDLIB_MODULE_MESSAGES = {'_gdbm': "Standard library module disabled during build '_gdbm' was not found",
 '_overlapped': 'Unsupported platform for Windows-only standard library module '
                "'_overlapped'",
 '_testcapi': "Standard library module disabled during build '_testcapi' was "
              'not found',
 '_testclinic': "Standard library module disabled during build '_testclinic' "
                'was not found',
 '_testclinic_limited': 'Standard library module disabled during build '
                        "'_testclinic_limited' was not found",
 '_testconsole': 'Unsupported platform for Windows-only standard library '
                 "module '_testconsole'",
 '_testlimitedcapi': 'Standard library module disabled during build '
                     "'_testlimitedcapi' was not found",
 '_winapi': 'Unsupported platform for Windows-only standard library module '
            "'_winapi'",
 '_wmi': "Unsupported platform for Windows-only standard library module '_wmi'",
 'msvcrt': 'Unsupported platform for Windows-only standard library module '
           "'msvcrt'",
 'nt': "Unsupported platform for Windows-only standard library module 'nt'",
 'winreg': 'Unsupported platform for Windows-only standard library module '
           "'winreg'",
 'winsound': 'Unsupported platform for Windows-only standard library module '
             "'winsound'",
 'xx': "Standard library module disabled during build 'xx' was not found",
 'xxlimited': "Standard library module disabled during build 'xxlimited' was "
              'not found',
 'xxlimited_35': "Standard library module disabled during build 'xxlimited_35' "
                 'was not found'}
